#!/bin/sh

# execute jupyter notebook

# change the working dir to the one where the script is (scripts/)
cd "${0%/*}" 

# convert notebook to python script
sudo jupyter nbconvert --to python --output simple_detector.py simple_detector.ipynb
sed -i '1 s/^/#!\/usr\/bin\/env python\n/' simple_detector.py

# run with the given arguments
python simple_detector.py "$@"